export const featuredProjectsQuery = `*[_type == "project" && featured == true] | order(sortOrder asc){
  _id,
  title,
  "slug": slug.current,
  shortSummary,
  projectType,
  engagement,
  featured,
  year,
  status,
  techStack[]-> { name },
  role,
  teamSize,
  problemStatement,
  constraints,
  approach,
  outcomes,
  metrics,
  liveUrl,
  repoUrl,
  sortOrder,
  seoTitle,
  seoDescription,
  featuredImage,
  galleryImages
}`;

export const allProjectsQuery = `*[_type == "project"] | order(sortOrder asc, year desc){
  _id,
  title,
  "slug": slug.current,
  shortSummary,
  projectType,
  engagement,
  featured,
  year,
  status,
  techStack[]-> { name },
  role,
  teamSize,
  problemStatement,
  constraints,
  approach,
  outcomes,
  metrics,
  liveUrl,
  repoUrl,
  sortOrder,
  seoTitle,
  seoDescription,
  featuredImage,
  galleryImages
}`;

export const projectBySlugQuery = `*[_type == "project" && slug.current == $slug][0]{
  _id,
  title,
  "slug": slug.current,
  shortSummary,
  fullDescription,
  projectType,
  engagement,
  featured,
  year,
  status,
  techStack[]-> { name },
  role,
  teamSize,
  problemStatement,
  constraints,
  approach,
  buildDetails,
  outcomes,
  metrics,
  liveUrl,
  repoUrl,
  sortOrder,
  seoTitle,
  seoDescription,
  featuredImage,
  galleryImages
}`;

export const siteSettingsQuery = `*[_type == "siteSettings"][0]{
  siteTitle,
  defaultSeoTitle,
  defaultSeoDescription,
  availabilityLabel,
  scrollLabel,
  selectedWorkHeading,
  selectedWorkDescription,
  selectedWorkCtaHeading,
  selectedWorkCtaDescription,
  selectedWorkMetricOneLabel,
  selectedWorkMetricTwoLabel,
  toolsEyebrow,
  toolsHeading,
  toolsDescription,
  tools,
  socialLinks,
  contactEmail,
  heroHeadline,
  heroSupportingText,
  footerText,
  credibilityItems
}`;

export const aboutPageQuery = `*[_type == "aboutPage"][0]{
  heading,
  introLabel,
  intro,
  story,
  principles,
  toolkit,
  portrait,
  spotlightTitle,
  spotlightSubtitle,
  arsenalHeading,
  arsenalDescription,
  languagesTitle,
  frameworksTitle,
  infrastructureTitle,
  infrastructureSummary,
  careerHeading,
  careerDescription,
  timeline,
  ctaHeading,
  ctaDescription,
  ctaPrimaryLabel,
  ctaSecondaryLabel
}`;

export const contactPageQuery = `*[_type == "contactPage"][0]{
  heading,
  supportingText,
  eyebrowLabel,
  panelHeading,
  panelBody,
  bestForTitle,
  bestForBody,
  responseTitle,
  responseBody,
  nameLabel,
  emailLabel,
  messageLabel,
  submitLabel,
  email,
  linkedIn,
  github
}`;

export const projectsPageQuery = `*[_type == "projectsPage"][0]{
  heading,
  supportingText,
  badgeText
}`;
